/**
 * The Customer Class is the basic blueprint for the customer. information required of the customer would be the name
 * and address. the id is automatically generated by the application.
 * @author Yusuf Dauda
 * @version 1.0
 */
public class Customer {
	private String firstName;
	private String lastName;
	private int id;
	private String address;

	/**
	 * @param firstName First name of customer.
	 * @param lastName Last name of customer.
	 * @param id is an automatically generated customer id.
	 */
	public Customer(String firstName, String lastName, int id) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastname) {
		this.lastName = lastname;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	
	public String toString() {
		return String.format("First Name: %S%nLast Name: %S%nCustID: %d%n"
				+ "Address: %s%n", firstName, lastName, id, address);
	}
}
